# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_user_updatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='his_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=30, verbose_name='主机')),
                ('filename', models.CharField(max_length=30, verbose_name='文件名')),
                ('service_type', models.CharField(max_length=30, verbose_name='服务类型')),
                ('status', models.IntegerField(verbose_name='发布状态')),
                ('relea_time', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='service_type',
            field=models.CharField(max_length=30, null=True, verbose_name='服务类型'),
        ),
    ]
