# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170324_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='host_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30, verbose_name='主机name')),
                ('ip', models.CharField(max_length=30, verbose_name='主机ip')),
                ('host_group', models.CharField(max_length=30, verbose_name='主机组')),
            ],
        ),
    ]
