# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20170328_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30, verbose_name='服务名称')),
                ('install_type', models.CharField(max_length=30, verbose_name='软件安装方式(rpm/源码编译)')),
                ('updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='添加时间')),
            ],
        ),
    ]
