# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='his_rel',
            name='host',
        ),
        migrations.AddField(
            model_name='his_rel',
            name='host_or_group',
            field=models.CharField(max_length=30, null=True, verbose_name='主机或主机组'),
        ),
        migrations.AlterField(
            model_name='service_type',
            name='install_type',
            field=models.CharField(max_length=30, verbose_name='软件安装方式(yum rpm/make 源码编译)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='headImg',
            field=models.FileField(upload_to='static/upload/', verbose_name='文件名'),
        ),
    ]
