# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20170329_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='his_rel',
            name='host_or_group',
        ),
        migrations.AddField(
            model_name='his_rel',
            name='host',
            field=models.CharField(max_length=30, null=True, verbose_name='主机'),
        ),
    ]
