# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20170329_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='his_rel',
            name='host_group',
            field=models.CharField(max_length=30, null=True, verbose_name='主机组'),
        ),
    ]
