# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_his_rel_host_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_type',
            name='demo_path',
            field=models.CharField(max_length=90, null=True, verbose_name='代码所在路径'),
        ),
    ]
