# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_service_type_demo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='server_ip_and_port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(max_length=30, verbose_name='服务端ip地址')),
                ('server_port', models.CharField(max_length=30, verbose_name='服务端port')),
            ],
        ),
    ]
