# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_server_ip_and_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='his_rool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=30, null=True, verbose_name='主机')),
                ('host_group', models.CharField(max_length=30, null=True, verbose_name='主机组')),
                ('filename', models.CharField(max_length=30, verbose_name='文件名')),
                ('service_type', models.CharField(max_length=30, verbose_name='服务类型')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('relea_time', models.DateTimeField(auto_now=True, verbose_name='回滚时间')),
            ],
        ),
        migrations.AlterField(
            model_name='server_ip_and_port',
            name='server_port',
            field=models.CharField(max_length=30, verbose_name='服务端port,\n是访问django的端口'),
        ),
        migrations.AlterField(
            model_name='service_type',
            name='demo_path',
            field=models.CharField(max_length=90, null=True, verbose_name='代码所在路径,如/var/www/html'),
        ),
    ]
