# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20170329_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_type',
            name='service_processname',
            field=models.CharField(max_length=30, null=True, verbose_name='服务进程名称'),
        ),
        migrations.AlterField(
            model_name='service_type',
            name='demo_path',
            field=models.CharField(max_length=90, null=True, verbose_name='代码所在路径,软连接要链到的地方,如/var/www/html'),
        ),
    ]
